Revert to relative paths
We need relative paths because the .deb artifacts get generated in
the parent directory of `source_dir`, so the source and results
directories should be relative to the parent directory and we have
to mount the parent directory, otherwise the artifacts won't be
visible outside of the docker build.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,11 +21,11 @@ inputs:
     description: 'The name (and relative path) of the .dsc file'
     required: true
   source_dir:
-    description: 'The absolute path to the directory that contains the .dsc file. Defaults to $GITHUB_WORKSPACE'
+    description: 'The path to the directory that contains the .dsc file, relative to `$GITHUB_WORKSPACE`. Defaults to `.`.'
     required: false
-    default: '${{github.workspace}}'
+    default: '.'
   result_dir:
-    description: 'The path to the directory where the built .deb files get copied to (relative to $source_dir; defaults to artifacts).'
+    description: 'The path to the directory where the built .deb files get copied to, relative to `$GITHUB_WORKSPACE`. Defaults to `artifacts`.'
     required: false
     default: 'artifacts'
   enable_llso:
@@ -82,8 +82,16 @@ runs:
 
     - name: Build package
       shell: bash
-      run: docker run --platform="${{inputs.platform}}" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "${{inputs.source_dir}}":/source --env INPUT_DISTRIBUTION --env INPUT_DIST --env INPUT_PLATFORM --env INPUT_SOURCEPACKAGE --env INPUT_SOURCE_DIR --env INPUT_RESULT_DIR --env INPUT_ENABLE_LLSO --env INPUT_ENABLE_PSO --env INPUT_DEB_FULLNAME --env INPUT_DEB_EMAIL --env INPUT_PRERELEASE_TAG --workdir /source "${IMAGE_NAME}"
-      working-directory: ${{inputs.source_dir}}
+      run: |
+        SOURCE_DIR="$(readlink -f "${{inputs.source_dir}}")"
+        DSC_DIR=$(realpath --relative-to="${{github.workspace}}" "${SOURCE_DIR}")
+
+        if [[ "$SOURCE_DIR" != "${{github.workspace}}"* ]]; then
+          echo "::error::`source_dir` (${INPUTS_SOURCE_DIR}) has to be a subdirectory of the current workdir!"
+          exit 2
+        fi
+        docker run --platform="${{inputs.platform}}" -v "/var/run/docker.sock":"/var/run/docker.sock" -v "${{github.workspace}}":/source --env INPUT_DISTRIBUTION --env INPUT_DIST --env INPUT_PLATFORM --env INPUT_SOURCEPACKAGE --env INPUT_SOURCE_DIR=${DSC_DIR} --env INPUT_RESULT_DIR --env INPUT_ENABLE_LLSO --env INPUT_ENABLE_PSO --env INPUT_DEB_FULLNAME --env INPUT_DEB_EMAIL --env INPUT_PRERELEASE_TAG --workdir /source "${IMAGE_NAME}"
+      working-directory: ${{github.workspace}}
       env:
         INPUT_DISTRIBUTION: "${{inputs.flavor}}"
         INPUT_DIST: "${{inputs.dist}}"
